### ISSUE TITLE
QXcbConnection: Could not connect to display 

### ISSUE THREAD

**Issue by tisjune** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#12]
When I attempt to import convokit into an ipython terminal, I get the following error: 
QXcbConnection: Could not connect to display 

This does not happen in notebooks or in actual python scripts.

**Comment by calebchiam** [comment]
This seems to have been caused by matplotlib using Qt5Agg in ConvoKit 1.0's version of QuestionTypology. See also: https://github.com/ipython/ipython/issues/10627.

No longer relevant after the refactoring done in ConvoKit 2.0 - and having tested this on the latest version (2.0.4), I can confirm that the error no longer appears.
