### ISSUE TITLE
[dataset] Switchboard

### ISSUE THREAD

**Issue by noameshed** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#28]
Dataset name: Switchboard

Description:
Switchboard contains transcripts of phone conversations between two people. Participants are given a topic to discuss and have a chance to introduce themselves before recording their discussion. The conversation metadata includes information about the conversation topic (both a short and long description), date, length (in minutes), and the ID of the caller ('from_caller') and receiver ('to_caller'). The user data includes the user's sex, education level, birth year, and dialect area. Utterance information includes the text spoken, the ID of the first utterance in the conversation, the timestamp, and the ID of the user the utterance is replying to. The metadata includes DAMSL tags, parts-of-speech (POS), and tree structure corresponding with the utterance. The DAMSL tags describe the statement type, for example 'question', 'non-verbal', 'hedge', etc.

Note that the original switchboard dataset did not split utterances by user, but rather by the associated tags. In the corpus we created, we combined consecutive utterances by the same user into one utterance. This is why the metadata tags are in the form of dictionaries, such that the keys are the utterance text segments and the values are the tags. 

Details:
See more detail in our [README.txt](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3705048/README.txt)
In our created corpus, the statistics are:
440 users, 122646 utterances, and 1155 conversations.

Licensing information:
The SWDA Switchboard work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License (see source [here](http://compprag.christopherpotts.net/swda.html)

Associated paper:
https://web.stanford.edu/~jurafsky/ws97/manual.august1.html

Contact:
Corpus translated into ConvoKit format by [Nathan Mislang](mailto:ntm39@cornell.edu), [Noam Eshed](mailto:ne236@cornell.edu), and [Sungjun Cho](mailto:sc782@cornell.edu).

Corpus link:
[corpus.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3705065/corpus.zip)

For our ConvoKit conversion and examples of its usage, take a look at our forked repo [here](https://github.com/noameshed/Cornell-Conversational-Analysis-Toolkit/tree/master/datasets/switchboard-corpus)

**Comment by liye** [comment]
Hi, 

Thanks for your work with converting SwDA, and sorry for the delayed response! Here are some comments:  

Description: 

- I wonder if it would be better to follow the original authors' convention of calling the corpus Switchboard Dialog Act Corpus (which I believe is where the SwDA shorthand comes from?), instead of Switchboard Telephone Conversation Corpus (which seems to refer to an earlier version that comes without dialog acts tags). 

- To be consistent with ConvoKit documentations, I think it might be helpful to include the original paper more directly/explicitly (i.e., providing citations & links, see other dataset docs for format). The corpus page could be included as a further detail, either as part of the description, or as part of Additional note (explained later). 

User-level information:

- it's probably worth mentioning that user names are taken from the numerical id in SwDA.  

- dialect_area: while the rest of the categories are self-explanatory, it it perhaps helpful to include some short note on how "MIXED" or "UNK" are decided

Utterance-level information: 

- reply_to should be None if the utterance is not a reply. 

- I wonder if a dictionary of text segment to corresponding tag/tree is the best structure to store such data. It seems redundant to have essentially three copies of texts (once in text fields, twice as dictionary keys), and it seems less intuitive to use? (e.g., consider if I want the sequence of dialog acts in the utterance, or count dialog-act bigrams -- I think the general comment is to structure it in a way that best fits the needs of an end-user, which you might have better ideas than I do.) Additionally, could you clarify how are the POS and parses obtained? (i.e., by humans or by some toolkits? -- I guess if it's all machine-labeled, they may seem less essential to include?)

Conversation-level/Corpus-level information:

- I think what's currently stored as corpus-level metadata should probably all go to conversation-level meta: since it's currently stored as a dictionary keyed by conversation ids, it seems more appropriate to leave the values to be in the meta fields for the conversation indexed by the key? 

Additional note 

- I think we would hope for a one-piece documentation that covers all necessary information. Currently the bulk of info is in the README file, but there are pieces that's only in the comment (e.g., Licensing information). I would suggest adding those to a new "Additional note" section (which most of ConvoKit datasets have) in the README . 

- Similarly, other "additional information", e.g., the special note under utterance that explains how the operationalization of an utterance differ with the original SwDA release, can be included in the same section . 

- This is optional, but it may also be helpful to leave some pointers for how speech is transcribed, so that users can have a feel of what various symbols (e.g., "{}", "+") in this context means. 

Other

As a stylistic note, you may want to consider using more descriptive text for the links your are including, and insert comma at appropriate positions in numbers (e.g., 221616 -> 221,616), for readability.  

Let me know if these comments make sense, and thanks again for your work!

**Comment by liye** [comment]
As a follow up, after discussing with Cristian, we think it may be cleaner to not include the pos and parse tree information for now, given that the dialog acts are the perhaps more essential annotation for ConvoKit users (unless there are serious issues you think that may arise). For dialog acts tags, we wonder if a list of (text, tag) tuples may be a better structure to store such data (so there is a more explicit signal for the ordering of text segments). 

Let me know if you have any questions, and thanks again for working on this!

**Comment by noameshed** [comment]
Thanks for your suggestions! We are working on applying these changes now.

You mentioned that reply_to should be None if the utterance is not a reply. Am I correct in understanding that you are referring to the very first utterance in each conversation? Since we are combining consecutive utterances by the same user, there should not be utterances in the middle of a conversation which are not directly replying to the previous speaker. Please let me know if I have understood correctly!

**Comment by liye** [comment]
Yes, I am referring to the very first utterance (i.e., root) in each conversation. I think currently its reply_to is the id of itself, but by ConvoKit convention, it should be None (as exemplified in other datasets, e.g., [here] (https://zissou.infosci.cornell.edu/convokit/documentation/chromium.html]).

**Comment by noameshed** [comment]
No problem, we'll make that update! In terms of the (text, tag) list format for the dialog tags, would you like that to be in the metadata, separate from the utterance text? Or would you prefer that we replace the utterance text with a list of the (text, tag) tuples?

**Comment by liye** [comment]
Thanks! With the (text, tag) list, I meant to have it to replace the dictionary of text segment to tag that's currently being stored in the metadata, utterance text should remain unchanged.

**Comment by noameshed** [comment]
We've made the updates you mentioned. Please let me know if there is anything we are missing or have misunderstood!

Our updated README is here: [README.txt](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3763903/README.txt)

Our updated corpus is here: [corpus.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3763907/corpus.zip)

**Comment by liye** [comment]
Some quick things:
1. Could you make the first reference of the paper in proper citation format (i.e., how you put in Related publications, starting with "Distributed together with")
2. Could you add in license information (which you had in your first comment) in the "Additional Note" section? 
3. Under "Usage and Stats", could you convert it to the style as the Chromium documentation linked above (i.e., stats comes directly from corpus.print_summary_stats())

**Comment by sc782** [comment]
Hello,

We've updated the README to reflect the changes in the metadata and also other information (reference, license information, etc.). Feel free to take a look at the forked repo [here](https://github.com/noameshed/Cornell-Conversational-Analysis-Toolkit/tree/master/datasets/switchboard-corpus), and let us know in case anything else comes up.

Thank you!

**Comment by liye** [comment]
Hi Thanks for the update! I checked out the current version under corpus in the linked repo, just to clarify: 

1) In the README, you mention that "Conversations are indexed by the original SwDa dataset IDs", but I think currently conversations are indexed by the id of the root (i.e., "4384-0" as opposed to "4384"). I don't think we have to align with SwDA id, but we probably do want to be accurate in the documentation. 

2) For some conversations there is the additional meta info of "filename", but not all conversations have that. Is there any reason why? This field is also not mentioned in the README, and I personally feel we may necessarily need to keep them, given that's it's more of a conversion detail that is less relevant for anyone doing conversational analysis with the corpus.

**Comment by noameshed** [comment]
You are right, I updated the README to document that we are using the roots of the SwDA IDs for the conversation IDs. Here's the updated README: [README.txt](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3802556/README.txt)

I'm a bit confused by your second point. Do you mean that we should get rid of the filename meta info, or that we should keep it? You said that you think we need to keep it, but follow that up by saying that it is not a relevant piece of information. Was this a typo, and you meant to say we do not necessarily need to keep it?

Thanks!

**Comment by liye** [comment]
Thanks for the update! Re 2, I did not mean that you need to keep it (my vote is no, unless you find particular reasons for such need). However, I was a bit confused about why some conversations have that meta field but others don't (presumably all conversations are read from some file?). So the earlier part of my comment is meant to say that it may be worth checking why there is such behavior, but not that they should be kept.

**Comment by sc782** [comment]
Hello, sorry to keep you waiting.

So I digged up the original data, and what I found was that in several files of the swda dataset, the ptb_basename field (which we transferred as "filename") was left blank, hence leaving meta fields in some conversations as empty. 

In fact, they don't actually coincide with the actual file names we get the transcripts, but I believe the developers of swda used those to denote the filenames in the raw data, not the data they released. So I'm guessing we have two choices: 1) We can keep the "filename" field, but instead use the filenames corresponding to the released version of the dataset, which could be useful? or 2) We can simply remove the "filename" field of conversations as you mentioned.

Let me know which you would prefer, and I'll update it accordingly. Thank you!

**Comment by liye** [comment]
Hi, thanks for getting back! Would using filenames corresponding to the released version provide information for people who want to look up for the parse trees (which I believe we decided to exclude?). If so, I think it would be good if we go with option 1).

**Comment by sc782** [comment]
Yup, the users will be able to look up corresponding parse trees in the original swda dataset with the filename. Let me update the dataset. Thanks!

**Comment by liye** [comment]
Hey, I am just wondering if you have found the time to make the edits you mentioned? (No worries if you were busy, it would also be helpful if you are willing to share any in-progress intermediates).

**Comment by sc782** [comment]
Oh sorry, I should have sent a confirmation. The edits have been made already, and updated in the repo. Feel free to take a look and give any feedback.

**Comment by liye** [comment]
Thanks! This corpus has now been integrated into ConvoKit (https://zissou.infosci.cornell.edu/convokit/documentation/switchboard.html)! Let me know in case you find any issues.

**Comment by sc782** [comment]
Will do. Thank you for your patience!

**Comment by calebchiam** [comment]
@all-contributors please add @sc782 for data

**Comment by calebchiam** [comment]
@all-contributors please add @noameshed for data
