### ISSUE TITLE
[dataset] Friends

### ISSUE THREAD

**Issue by emtseng** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#29]
**Dataset name**: Friends

**Description**: A collection of all the conversations that occurred over 10 seasons of Friends, a popular American TV sitcom that ran in the 1990s. The corpus includes the following data and metadata:

- **User-level:** Users are characters. They are indexed by their names (i.e. 'Monica Geller'), and each User comes with metadata for the episode of their first appearance and their gender.

- **Utterance-level:** Utterances are indexed according to their ID 'sXX-eYY-cZZ-uAAA', where XX denotes the season (e.g. 01), YY denotes the episode (e.g. 01), ZZ denotes the conversation (e.g. 01), and AAA denotes the utterance within that conversation (e.g. 001). Each Utterance comes with the text of the utterance and the character (or User) speaking. The available metadata varies by seasons, but can include: character entities (or who is referred to in the utterance), emotion, a tokenized version of the text, caption information, and notes about the transcript.

- **Conversation-level:** Conversations represent scenes of the show. They are indexed by the id of the first utterance of a conversation.

**Details:** See more in our [README.md](https://github.com/emtseng/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/friends-corpus/README.md). In terms of summary statistics, the corpus includes the following: Across 10 seasons there are 236 episodes, 3,107 scenes, 61,309 utterances.

**Licensing information:** The data for this project was obtained from Jinho D. Choi and the Emory NLP team ([source](https://github.com/emorynlp/character-mining)). It is copyright 2015, Emory University, and licensed under [the Apache License, v.2.0](https://github.com/emorynlp/character-mining/blob/master/LICENSE.txt).

**Contact:** Corpus prepared for ConvoKit by [Emily Tseng](mailto:et397@cornell.edu), [Nianyi Wang](mailto:nw344@cornell.edu), and [Katharine Sadowski](mailto:ks2373@cornell.edu).

**Link:** [corpus.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3714342/corpus.zip)

For our ConvoKit conversion and examples of the corpus's usage, see our [forked repo](https://github.com/emtseng/Cornell-Conversational-Analysis-Toolkit).

**Comment by calebchiam** [comment]
Hi Emily, thanks for this submission! I can see a lot of thought has gone into converting this corpus, and here are some changes that you might want to consider before we integrate this into ConvoKit:

1. Since Conversations represent scenes of the show, and you have an intuitive structure for naming utterances, perhaps you'd like to use that structure for **indexing conversations** instead of naming the conversation after the first utterance? ('s01_e01_c01_u001' (current) -> 's01_e01_c01' (proposed)). This is for clarity in naming.

2. **What kind of metadata should Conversations have?** Conversations have no metadata at the moment, but following the original dataset, we might expect Conversations (which correspond to scenes) to have metadata on the 'Season', 'Episode', and 'Scene no.' they belong to. This makes it more usable, e.g. you might imagine that a user would want to filter for the 1st and 2nd scenes in all episodes of the 1st season for some kind of analysis.

It's fine (good, actually) for this information to be stored (and repeated) in Utterance metadata as well, as it currently is. 

3. **Utterance reply_to:** There are several Utterances (that are not the first in the conversation) with reply_to = None. This seems to have arisen because you've chosen to exclude Utterances like "[Time Lapse, Ross has entered.]". 

In the interest of preserving the original dataset to the greatest degree possible, I think it would be okay to include Utterances like the above. (Just a unique kind of Utterance for scripted formats, maybe.) Another issue with the current structure is that you have Conversation threads with broken sequences (because you've excluded these utterances.) So overall, I lean toward including these Utterances.

This is admittedly tricky though, maybe @cristiandnm can advise?

4. **user metadata**: As this is meant to be a convokit conversion of the original dataset, we would not include this newly added metadata 'gender' (from your gender_guesser module) or 'first_appearance'.

5. **character_entities**: Could you add a note in your README to explain how to interpret this data? e.g. what does [[8, 9, "Monica Geller"], [12, 13, "Judy Geller"]] mean?

Let me know what you think, and thank you again for your work on this!

**Comment by emtseng** [comment]
Sure thing, thanks Caleb. We'll make your requested edits for 1, 4 and 5, and we'll look into 3. 

w.r.t. 2: I understand the utility of being able to filter by episode/scene/season -- could that not already be achieved using the information in the indices? i.e. "s01_e01_c01"

**Comment by calebchiam** [comment]
You're correct that we could filter by the convo_id, but it's a somewhat 'hacky' way to do it. It would however require quite a bit more effort from the user to filter for certain scenes themselves, e.g. I'd have to use regex / split() functionality to parse the id manually.

In general, most/all of the current ConvoKit datasets don't use structured convo ids. I do think the current naming convention is pretty nice, but it should not be the primary way for users to filter for scene characteristics.

Thanks Emily!

**Comment by cristiandnm** [comment]
Emily and Team,  checking in on the status here.

**Comment by emtseng** [comment]
Thanks for checking in, Cristian. Updates below. Let me know of other changes that need to be made.

--

**Dataset name:** Friends

**Description:** A collection of all the conversations that occurred over 10 seasons of Friends, a popular American TV sitcom that ran in the 1990s. The corpus includes the following data and metadata:

**User-level:** Users are characters. They are indexed by their names (i.e. 'Monica Geller').

**Utterance-level:** Utterances are indexed according to their ID `sXX-eYY-cZZ-uAAA`, where XX denotes the season (e.g. 01), YY denotes the episode (e.g. 01), ZZ denotes the conversation (e.g. 01), and AAA denotes the utterance within that conversation (e.g. 001). Each Utterance comes with the text of the utterance and the character (or User) speaking. The available metadata varies by seasons, but can include: character entities (or who is referred to in the utterance), emotion, a tokenized version of the text, caption information, and notes about the transcript.

**Conversation-level:** Conversations represent scenes of the show. They are indexed by the id `sXX-eYY-cZZ`, where XX denotes the season (e.g. 01), YY denotes the episode (e.g. 01), ZZ denotes the conversation (e.g. 01). Each Conversation comes with a list of the constituent Utterances, and metadata on the season, episode, and scene it represents.

**Details:** See more in our [README.md](https://github.com/emtseng/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/friends-corpus/README.md). In terms of summary statistics, the corpus includes the following: Across 10 seasons there are 236 episodes, 3,107 scenes/conversations, and 67,373 utterances.

**Licensing information:** The data for this project was obtained from Jinho D. Choi and the Emory NLP team (source). It is copyright 2015, Emory University, and licensed under the Apache License, v.2.0.

**Contact:** Corpus prepared for ConvoKit by Emily Tseng, Nianyi Wang, and Katharine Sadowski.

**Link:** [friends-corpus.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3747240/friends-corpus.zip)

See our [forked repo](https://github.com/emtseng/Cornell-Conversational-Analysis-Toolkit) for examples of the corpus's usage, and [this notebook](https://github.com/emtseng/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/friends-corpus/convert_convokit.ipynb) for our ConvoKit-specific conversion.

**Comment by calebchiam** [comment]
The corpus has been successfully integrated into ConvoKit! You can now download it at `friends-corpus`.

**Comment by calebchiam** [comment]
@all-contributors please add @emtseng for data

**Comment by calebchiam** [comment]
@all-contributors please add @kcsadow for data

**Comment by calebchiam** [comment]
@all-contributors please add @emtseng for data
