### ISSUE TITLE
[dataset] Persuasion for Good

### ISSUE THREAD

**Issue by dn273** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#31]
**Dataset name**: Persuasion for Good

**Description**: A large metadata-rich collection of online conversations between two people where one participant ("persuader") is trying to convince the other ("persuadee") to donate to a charity. This dataset contains 1017 dialogues, each with several conversational turns. Additionally, every user has a personality vector associated with them generated through psycological surveys.

Distributed together with: "Persuasion for Good: Towards a Personalized Persuasive Dialogue System for Social Good" https://arxiv.org/pdf/1906.06725.pdf. Xuewei Wang et al. ACL 2019.

**Dataset details:**
Original data: https://gitlab.com/ucdavisnlp/persuasionforgood/tree/master/data

- User-level information: Users in this dataset are Amazon Turks. For each user, the authors provide a 23-dimension characteristic vector based on a pre-task psychological survey. Each of these personality characteristics takes on a value from 1 to 6; in addition, demographic info such as age, sex, race, education, marital status, employment, income, religion, and ideology are also included as user-level metadata. 

- Utterance-level information:
For each utterance, we provide: 
id: index of the utterance
user: the user who authored the utterance
root: index of the conversation root of the utterance
reply_to: index of the utterance to which this utterance replies to (None if the utterance is the first utterance in a conversation.)
text: textual content of the utterance
er_label_1: first persuasion strategy used by the persuader
ee_label_1: first persuasion strategy used by the persuadee
er_label_2: second persuasion strategy used by the persuader
ee_label_2: second persuasion strategy used by the persuadee
neg : The negative sentiment of the utterance
neu : The neutral sentiment of the utterance
pos : The positive sentiment of the utterance
Metadata for utterances include:
dialogue_idx: index of the dialogue from which this utterance occurs
role: whether the utterance is spoken by the persuader ("0") or persuadee ("1")
num_turns: The particular turn in which this utterance occurs in the dialogue

- Conversational-level information:
Conversations are indexed by the id of the dialogue. Conversation metadata now includes donation amount, num of turns, intended donation amount (only available for 300 annotated conversations), and the persuader/persuadee user ids.

**Licensing information**: The data for this project was obtained from Xuewei Wang et al. ACL 2019[https://gitlab.com/ucdavisnlp/persuasionforgood](url). 

**Related Publication:** 
[https://arxiv.org/abs/1906.06725](url)

**Contact Information:**
Please email any questions to: fl338@cornell.edu, gd3435@cornell.edu, dn273@cornell.edu (Frank Li, Grace Deng, Di Ni).

**Link:** 
[p4g_corpus.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3718492/p4g_corpus.zip)

**Comment by tisjune** [comment]
Hi, 
thanks for your work on this! More comments coming, but for now, could you point me to a repository you worked with in converting this dataset, and/or the code you used to perform the conversion?

**Comment by dn273** [comment]
Hi Justine,

Our repository is here :
https://github.com/junfrankli/Cornell-Conversational-Analysis-Toolkit/tree/master/datasets/persuasion_corpus


and  dataconversion file is:
https://github.com/junfrankli/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/persuasion_corpus/DataConversion.ipynb

**Comment by tisjune** [comment]
Okay, got it! I see that the user-level metadata description is more expanded -- thanks! My other comments are still standing, I think -- let me know what you think.

**Comment by tisjune** [comment]
A few more things:
- It would be great if you could clean up the data conversion file to only encapsulate the data conversion steps you've taken (and as a quick pointer, calling `pd.read_csv` to read in all the csv files should fix some of the datatype problems, regarding ints being stored as strings)
- Try calling `convo.add_meta` to add conversation-level meta instead of assigning to `conversation.meta` -- this might help fix the missing conversation-level metadata.
- I also noticed that in the paper, both the persuader and persuadee can offer donations, but it seems that you only have donation values for one person.

**Comment by cristiandnm** [comment]
Hi Team,

Since we did not hear from you and there seems to have been several major issues with your corpus and documentation,* Justine went ahead and addressed them herself.  If you are curious, you can go ahead and test the corpus on the convokit main website and let us know if you see any issues.  I am going to close this task now.

*(some of the issues that Justine mentioned were brought up before in our discussions)

**Comment by calebchiam** [comment]
@all-contributors please add @dn273 for data

**Comment by calebchiam** [comment]
@all-contributors please add @gdeng96 for data

**Comment by calebchiam** [comment]
@all-contributors please add @junfrankli for data
