### ISSUE TITLE
Reddit bz2 to data format?

### ISSUE THREAD

**Issue by debajyotidatta** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#52]
Hi, 

This is great~! This will save me so much time, formatting some bz2 files.

In the documentation, it says that the conversations in the Reddit threads are till October 2018. I was wondering where is the script to convert from .bz2 files from pushshift.io to a corpus object?

**Comment by calebchiam** [comment]
Hi @debajyotidatta, glad you're finding ConvoKit useful for your work! 

We have the script and the infrastructure for converting it in a separate repository since the size of Reddit means that more careful engineering is required for conversion. For most datasets, we generate the Corpus with converted Utterances and then dump it to create the distributable dataset. This first approach may be unfeasible for Reddit depending on your computing resources and the size of what you're trying to convert. In our case, we wrote out the individual component files (i.e. conversations.json, utterances.jsonl, etc) directly. 

Here is a gist of our main conversion file: https://gist.github.com/calebchiam/711e47ce836f29c0ff889c903747c91f. 

This was written in 2018, so some parts may need to be updated depending on how Pushshift has changed its own data format. Feel free to tweak it to your purposes and let us know if you have any further questions!
