### ISSUE TITLE
Is there examples for converting the Reddit data into ConvoKit format

### ISSUE THREAD

**Issue by TaoRuan-Campus** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#68]
Hello. I notice that many of the examples in the document are from Reddit data. I am wondering:

1. Whether I can find examples of constructing ConvoKit format from Reddit dataset like https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/examples/converting_movie_corpus.ipynb;

2. Whether there are any good approaches to converting Pandas dataframe to the corpus format?

I am asking this because I would like to test the Fightin Words algorithm based on my own Reddit data as shown in https://convokit.cornell.edu/documentation/tutorial.html#setup but I only have Pandas dataframe of the Reddit data.

Thank you for your attention and look forward to your kind reply!

**Comment by calebchiam** [comment]
Hi @TaoRuan-Campus, we don't offer a script from converting from Pandas dataframes to the Corpus format because it isn't necessarily clear what columns of a pandas dataframe map to the fields in a Corpus component object. 

I would recommend just initialising the Speakers and Utterances directly and constructing a Corpus from there. If the movie-corpus example feels a bit opaque, you could try following this [simpler example](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/friends-corpus/convert.ipynb) instead.

In general, the high-level steps for corpus construction are:

1. Initialize Speaker objects with fields and metadata
2. Initialize Utterance objects with fields and metadata, passing in the Speaker objects in the Utterance constructor
3. Construct Corpus from Utterances, using `Corpus(utterances=[list of utterance objects])`
4. The Corpus constructs Conversations from the Utterances. You can then add metadata to the Conversation objects

Let us know how it goes!

**Comment by liye** [comment]
As a not-so-standard alternative, if speaker information is not important in your particular use case, you may refer to this [example](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/politeness-corpus/convert_politeness_corpus.py) that works directly with a pandas dataframe (but assumes a generic speaker). 

PS: Depending on what's included in your dataframe, you may want to make some modifications to make utterance-level information more complete, e.g., timestamp and reply_to information were not meaningful in the example corpus but can be of interest in your use case.

**Comment by TaoRuan-Campus** [comment]
Thank @liye and @calebchiam for your kind reply. Yes, I have constructed the required corpus format from my data frame based on the example. 
Maybe adding some standard features in ConvoKit to convert Pandas dataframe to the required format should be of great help. Pandas should be one of the most popular ways to analyze data, after all. For example, specifying which columns are corresponding to idx, conversation id, text, reply_to, speaker information and meta information and then a format can be generated.

**Comment by calebchiam** [comment]
Glad you could get it to work and thanks for the feedback, we'll consider including dataframe conversion as a more fully supported option for initialising a Corpus.
