### ISSUE TITLE
[Question] Is it possible to download your entire Reddit corpus? 

### ISSUE THREAD

**Issue by santoshbs** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#72]
I understand that your Reddit corpus is based on several thousand subreddits. Is it possible to download the entire Reddit corpus (not just the small collection) you have prepared?

Thanks,
sbs

**Comment by calebchiam** [comment]
We offer each subreddit as a separate downloadable corpus, which can be downloaded using `download('subreddit-[name]')`. (See [our docs](https://convokit.cornell.edu/documentation/subreddit.html) for more details.) There is no single Corpus for the entirety of Reddit though because that would be too large for us to use/distribute.

**Comment by liye** [comment]
If you would like to download most/all of reddit data, I would recommend getting the list of subreddits we offer by checking the subreddits listed within each folder [here](https://zissou.infosci.cornell.edu/convokit/datasets/subreddit-corpus/corpus-zipped/) (the filenames are all in the format of `[name].corpus.zip`), and then download them individually.

**Comment by santoshbs** [comment]
> If you would like to download most/all of reddit data, I would recommend getting the list of subreddits we offer by checking the subreddits listed within each folder [here](https://zissou.infosci.cornell.edu/convokit/datasets/subreddit-corpus/corpus-zipped/) (the filenames are all in the format of `[name].corpus.zip`), and then download them individually.

Many thanks! I have downloaded them.
